In [8]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import scipy.io as sio

In [13]:
#punto 1
matriz_4d=np.random.randint(4, size=(30,20,20,10))
print(matriz_4d)


[[[[1 2 1 ... 2 0 3]
   [2 1 3 ... 0 1 0]
   [3 3 0 ... 2 1 1]
   ...
   [3 1 1 ... 2 2 1]
   [2 2 3 ... 0 1 3]
   [2 3 1 ... 3 0 1]]

  [[2 1 0 ... 3 0 0]
   [3 0 0 ... 0 1 2]
   [2 1 0 ... 3 3 0]
   ...
   [2 3 2 ... 3 2 2]
   [1 3 0 ... 2 3 3]
   [1 0 3 ... 2 2 0]]

  [[2 3 3 ... 0 1 0]
   [2 3 0 ... 1 2 2]
   [2 0 3 ... 1 1 2]
   ...
   [3 1 1 ... 3 0 2]
   [3 1 1 ... 2 3 3]
   [3 0 3 ... 2 3 2]]

  ...

  [[0 2 0 ... 0 1 1]
   [0 1 3 ... 1 1 0]
   [3 3 1 ... 3 1 2]
   ...
   [2 2 2 ... 3 1 1]
   [3 2 0 ... 1 2 3]
   [1 1 0 ... 1 0 2]]

  [[0 2 1 ... 2 0 2]
   [1 2 0 ... 0 0 2]
   [3 1 3 ... 0 2 3]
   ...
   [1 3 2 ... 0 1 0]
   [3 0 1 ... 2 1 1]
   [1 0 1 ... 3 0 1]]

  [[1 1 1 ... 3 2 2]
   [2 0 3 ... 1 2 0]
   [3 1 3 ... 0 2 3]
   ...
   [2 3 2 ... 1 1 0]
   [3 0 3 ... 0 2 1]
   [1 1 1 ... 3 3 2]]]


 [[[3 1 3 ... 2 2 1]
   [3 0 3 ... 3 3 1]
   [0 3 2 ... 3 2 1]
   ...
   [3 1 3 ... 2 1 3]
   [2 0 2 ... 2 2 2]
   [2 2 1 ... 3 3 3]]

  [[3 3 0 ... 3 1 1]
   [1 2 3 ... 3 3 1]
   [

In [15]:
#punto 2
matriz_3d=matriz_4d[:,:,:,0].copy()
print(matriz_3d)

[[[1 2 3 ... 3 2 2]
  [2 3 2 ... 2 1 1]
  [2 2 2 ... 3 3 3]
  ...
  [0 0 3 ... 2 3 1]
  [0 1 3 ... 1 3 1]
  [1 2 3 ... 2 3 1]]

 [[3 3 0 ... 3 2 2]
  [3 1 3 ... 0 1 1]
  [3 3 2 ... 1 0 1]
  ...
  [2 0 0 ... 2 2 0]
  [0 3 1 ... 3 2 1]
  [0 2 1 ... 1 3 2]]

 [[0 2 1 ... 0 3 1]
  [0 0 1 ... 1 3 3]
  [1 1 2 ... 3 1 1]
  ...
  [1 0 2 ... 3 1 1]
  [2 1 0 ... 1 0 3]
  [2 2 2 ... 0 3 0]]

 ...

 [[1 3 3 ... 3 3 3]
  [1 0 2 ... 1 1 2]
  [2 3 0 ... 0 3 1]
  ...
  [2 0 2 ... 3 3 1]
  [3 0 3 ... 1 3 1]
  [3 3 3 ... 0 2 2]]

 [[1 3 0 ... 0 0 2]
  [2 3 3 ... 1 3 3]
  [0 0 1 ... 0 1 1]
  ...
  [2 1 1 ... 2 1 1]
  [0 3 3 ... 1 0 3]
  [1 1 2 ... 1 1 0]]

 [[1 0 0 ... 1 2 0]
  [0 0 2 ... 3 1 1]
  [3 2 3 ... 2 2 2]
  ...
  [2 1 2 ... 3 1 2]
  [0 3 1 ... 1 0 0]
  [3 3 2 ... 3 3 3]]]


In [16]:
#punto 3: atributos 
print(matriz_3d.ndim)
print(matriz_3d.shape)
print(matriz_3d.size)
print(matriz_3d.dtype)
print(matriz_3d.itemsize)
print(matriz_3d.nbytes)



3
(30, 20, 20)
12000
int32
4
48000
